# Generated by Django 2.0.7 on 2019-02-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_post',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
