# Generated by Django 2.0.7 on 2019-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190219_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='title',
            field=models.CharField(default='Not inserted', max_length=80),
        ),
    ]
