# Generated by Django 2.0.7 on 2019-01-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Percentage',
            field=models.CharField(max_length=8),
        ),
    ]
