# Generated by Django 2.0.7 on 2019-01-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190103_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
