# Generated by Django 2.0.7 on 2019-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='present',
            field=models.BooleanField(),
        ),
    ]
