# Generated by Django 2.0.7 on 2019-01-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190104_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='present',
            field=models.BooleanField(default='False'),
        ),
    ]
