# Generated by Django 2.0.7 on 2019-01-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190104_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
