# Generated by Django 2.0.7 on 2019-01-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190104_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=40)),
                ('Marks', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='product',
            new_name='Detail',
        ),
    ]
