# Generated by Django 2.0.7 on 2019-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190105_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Division',
            field=models.CharField(choices=[(80, 'Distinction'), (60, 'First Division'), (50, 'Second Division'), (40, 'Third Division')], default='Dist', max_length=40),
        ),
    ]
