# Generated by Django 2.0.7 on 2019-01-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_detail_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Division',
            field=models.CharField(choices=[('Dist', 'Distinction'), ('First', 'First Division'), ('Second', 'Second Division'), ('Third', 'Third Division')], default='Dist', max_length=40),
        ),
    ]
