# Generated by Django 2.0.7 on 2019-01-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_failed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='present',
            new_name='Present',
        ),
    ]
