# Generated by Django 2.0.7 on 2019-01-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190111_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Failed',
        ),
    ]
