# Generated by Django 2.0.7 on 2019-01-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_delete_failed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='Percentage',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='Present',
        ),
    ]
