# Generated by Django 2.0.7 on 2019-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190112_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Email',
            field=models.EmailField(default='Some_String', max_length=70),
        ),
    ]
