# Generated by Django 2.0.7 on 2019-01-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_detail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Desctiption',
            field=models.CharField(default='No description inserted', max_length=200),
        ),
    ]
