# Generated by Django 2.0.7 on 2019-01-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190118_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Description',
            field=models.CharField(max_length=200),
        ),
    ]
