# Generated by Django 2.0.7 on 2019-01-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190118_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
