# Generated by Django 2.0.7 on 2019-01-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_search_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_class',
            name='number',
        ),
        migrations.AddField(
            model_name='search_class',
            name='ID',
            field=models.IntegerField(default=1),
        ),
    ]
