# Generated by Django 2.0.7 on 2019-01-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20190120_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_class',
            old_name='ID',
            new_name='IDs',
        ),
    ]
