# Generated by Django 2.0.7 on 2019-01-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20190120_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_class',
            old_name='IDs',
            new_name='numbs',
        ),
    ]
