# Generated by Django 2.0.7 on 2019-01-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190120_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search_class',
        ),
    ]
