# Generated by Django 2.0.7 on 2019-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='sn',
            field=models.IntegerField(default=1),
        ),
    ]
