# Generated by Django 2.0.7 on 2019-01-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_detail_sn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
